apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: k8s
  name: mattermost
  
spec:
  selector:
    matchLabels:
      name: mattermost-operator
  namespaceSelector:
    matchNames:
      - mattermost
  endpoints:
    - interval: 30s
      path: /metrics
      params:
        format: 
          - prometheus
      port: http-metrics
      scheme: http
      
      jobLabel: mattermost-metrics
