{{- if and .Values.networkPolicies.enabled .Values.istio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: mattermost
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            {{- if .Values.networkPolicies.istioNamespaceSelector }}
            app.kubernetes.io/name: {{ .Values.networkPolicies.istioNamespaceSelector.ingress }}
            {{- else }}
            app.kubernetes.io/name: "istio-controlplane"
            {{- end }}
        podSelector:
          matchLabels:
            {{- toYaml .Values.networkPolicies.ingressLabels | nindent 12 }}
      ports:
      - port: 8065
        protocol: TCP
{{- end }}