{{- if and .Values.networkPolicies.enabled .Values.waitJob.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-wait-job-api-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      job-name: mattermost-wait-job
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
{{- end }}