{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.clusterAuditor.enabled -}}
{{- $namespace := $.Release.Namespace -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-cluster-auditor
  namespace: {{ $namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ .Values.istio.hardened.clusterAuditor.namespace }}
{{- end }}
