{{- if .Values.minio.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: default-minio-bucket-creation
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: default-minio-bucket-creation
    spec:
      imagePullSecrets:
      {{- with .Values.global.imagePullSecrets }}
      {{ . | toYaml | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: minio-bucket-creation
          image: {{ .Values.minio.bucketCreationImage }}
          command:
            - /bin/sh
            - -c
            - |
              set -ex
              attempt_counter=0
              max_attempts=25
              until [ $(mc config host add bigbang http://{{ .Values.minio.service.nameOverride }} {{ .Values.minio.tenants.secrets.accessKey }} {{ .Values.minio.tenants.secrets.secretKey }} >/dev/null; echo $?) -eq 0 ]; do
               if [ ${attempt_counter} -eq ${max_attempts} ];then
                  echo "Max attempts reached"
                  exit 1
                fi
                attempt_counter=$(($attempt_counter+1))
                sleep 10
              done
              mc mb bigbang/mattermost            
{{- end }}
