apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "mattermost.labels" . | nindent 4 }}
    app.kubernetes.io/component: "instance"
spec:
  image: {{ .Values.image.name }}
  imagePullPolicy: {{ .Values.image.imagePullPolicy }}
  {{- with .Values.global.imagePullSecrets }}
  imagePullSecrets:
  {{- toYaml . | nindent 4 }}
  {{- end }}

  size: {{ .Values.users }}users
  version: {{ .Values.image.tag }}
  replicas: {{ .Values.replicaCount }}

  {{- if .Values.istio.chat.hosts }}
  ingressName: {{ tpl (index .Values.istio.chat.hosts 0) $ }}
  {{- else }}
  ingressName: "chat.bigbang.dev"
  {{- end }}

  {{- if and .Values.enterprise.enabled .Values.enterprise.license }}
  licenseSecret: "mattermost-license"
  {{- end }}

  {{- if or .Values.mattermostEnvs .Values.sso.enabled .Values.minio.install .Values.existingSecretEnvs }}
  mattermostEnv:
  {{- range $k, $v := .Values.mattermostEnvs }}
  - name: {{ $k }}
    valueFrom:
      secretKeyRef:
        key: {{ $k }}
        name: "mattermost-envs"
  {{- end }}
  {{- if .Values.sso.enabled }}
  - name: MM_GITLABSETTINGS_ENABLE
    valueFrom:
      secretKeyRef:
        key: MM_GITLABSETTINGS_ENABLE
        name: "mattermost-envs"
  - name: MM_GITLABSETTINGS_ID
    valueFrom:
      secretKeyRef:
        key: MM_GITLABSETTINGS_ID
        name: "mattermost-envs"
  - name: MM_GITLABSETTINGS_SECRET
    valueFrom:
      secretKeyRef:
        key: MM_GITLABSETTINGS_SECRET
        name: "mattermost-envs"
  - name: MM_GITLABSETTINGS_AUTHENDPOINT
    valueFrom:
      secretKeyRef:
        key: MM_GITLABSETTINGS_AUTHENDPOINT
        name: "mattermost-envs"
  - name: MM_GITLABSETTINGS_TOKENENDPOINT
    valueFrom:
      secretKeyRef:
        key: MM_GITLABSETTINGS_TOKENENDPOINT
        name: "mattermost-envs"
  - name: MM_GITLABSETTINGS_USERAPIENDPOINT
    valueFrom:
      secretKeyRef:
        key: MM_GITLABSETTINGS_USERAPIENDPOINT
        name: "mattermost-envs"
  {{- end }}
  {{- if .Values.minio.install }}
  - name: MM_FILESETTINGS_AMAZONS3SSL
    valueFrom:
      secretKeyRef:
        key: MM_FILESETTINGS_AMAZONS3SSL
        name: "mattermost-envs"
  {{- end }}
  {{- if .Values.elasticsearch.enabled }}
  - name: MM_ELASTICSEARCHSETTINGS_CONNECTIONURL
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_CONNECTIONURL
        name: "mattermost-envs"
  - name: MM_ELASTICSEARCHSETTINGS_ENABLEAUTOCOMPLETE
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_ENABLEAUTOCOMPLETE
        name: "mattermost-envs"
  - name: MM_ELASTICSEARCHSETTINGS_ENABLEINDEXING
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_ENABLEINDEXING
        name: "mattermost-envs"
  - name: MM_ELASTICSEARCHSETTINGS_INDEXPREFIX
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_INDEXPREFIX
        name: "mattermost-envs"        
  - name: MM_ELASTICSEARCHSETTINGS_BULKINDEXINGTIMEWINDOWSECONDS
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_BULKINDEXINGTIMEWINDOWSECONDS
        name: "mattermost-envs"        
  - name: MM_ELASTICSEARCHSETTINGS_ENABLESEARCHING
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_ENABLESEARCHING
        name: "mattermost-envs"
  - name: MM_ELASTICSEARCHSETTINGS_SKIPTLSVERIFICATION
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_SKIPTLSVERIFICATION
        name: "mattermost-envs"
  - name: MM_ELASTICSEARCHSETTINGS_SNIFF
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_SNIFF
        name: "mattermost-envs"
  - name: MM_ELASTICSEARCHSETTINGS_USERNAME
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_USERNAME
        name: "mattermost-envs"
  - name: MM_ELASTICSEARCHSETTINGS_PASSWORD
    valueFrom:
      secretKeyRef:
        key: MM_ELASTICSEARCHSETTINGS_PASSWORD
        name: "mattermost-envs"             
  {{- end }}  
  {{- range .Values.existingSecretEnvs }}
  - {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- end }}

  # Give MM enough time to keel over if needed
  probes:
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 120

  scheduling:
    resources:
    {{- toYaml .Values.resources | nindent 6 }}

    {{- if .Values.affinity }}
    affinity:
      {{ toYaml .Values.affinity | nindent 6 }}
    {{- end }}

    {{- if .Values.nodeSelector }}
    nodeSelector:
      {{ toYaml .Values.nodeSelector | nindent 6 }}
    {{- end }}  

  {{- with .Values.volumes }}
  volumes:
  {{- toYaml . | nindent 4}}
  {{- end }}

  {{- with .Values.volumeMounts }}
  volumeMounts:
  {{- toYaml . | nindent 4}}
  {{- end }}

  database:
    external:
      secret: {{ .Values.database.secret | default (printf "%s-dbcreds" (include "mattermost.fullname" .)) }}

  fileStore:
    external:
      url: {{ .Values.fileStore.url | default .Values.minio.service.nameOverride }}
      bucket: {{ .Values.fileStore.bucket | default "mattermost" }}
      secret: {{ .Values.fileStore.secret | default .Values.minio.tenants.secrets.name }}
