{{- if and (not .Values.fileStore.secret) .Values.minio.install }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mattermost.fullname" . }}-objstore-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "mattermost.labels" . | nindent 4 }}
    app.kubernetes.io/component: "objectstorage"
data:
  accesskey: {{ .Values.minio.accessKey | b64enc }}
  secretkey: {{ .Values.minio.secretKey | b64enc }}
{{- end }}
