{{- if .Values.istio.enabled -}}
## Need to templatize this is for testing in bigbang.dev
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mattermost-mattermost-enterprise-edition
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "chat.bigbang.dev"
  gateways:
  - istio-system/main
  http:
  - route:
    - destination:
        host: mattermost-mattermost-enterprise-edition.mattermost.svc.cluster.local
        port:
          number: 8065
{{- end }}