{{- /* Render Istio ServiceEntries */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-chat
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  {{- range .Values.istio.chat.hosts }}
    - {{ tpl . $ }}
  {{- end }}
  location: MESH_EXTERNAL
  exportTo: 
  - "."
  ports:
    - number: 443
      protocol: TLS
      name: https
---
{{- end -}}
