{{- /* Render Istio ServiceEntries */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-mattermost
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - securityupdatecheck.mattermost.com
    - customers.mattermost.com
    - notices.mattermost.com
    - api.integrations.mattermost.com
    - pdat.matterlytics.com
    - api.github.com               # Workspace Optimization
  location: MESH_EXTERNAL
  exportTo: 
  - "."
  ports:
    - number: 443
      protocol: TLS
      name: https
---
{{- end -}}
