{{- /* Render Istio ServiceEntries */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.sso.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-mattermost
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - {{ include "sso.host" $ }}
  location: MESH_EXTERNAL
  exportTo: 
  - "."
  ports:
    - number: 443
      protocol: TLS
      name: https
---
{{- end -}}

