apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "minio.labels" . | nindent 4 }}
    app.kubernetes.io/component: "objectstorage"
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
