FROM registry1.dsop.io/ironbank/opensource/mattermost/mattermost:5.27.0

COPY --chown=mattermost:mattermost en.json /mattermost/client/i18n/en.json
COPY --chown=mattermost:mattermost root.html /mattermost/client/root.html
COPY --chown=mattermost:mattermost p1-bg.jpg /mattermost/client/images/p1-bg.jpg
